### ISSUE TITLE
LDN applications are not closing after 14 days

### ISSUE THREAD

**Issue by Lord-Bach** [keyko-io/filecoin-verifier-frontend#811]
**Describe the bug**
LDN applications that do not have any activity over 14 days (comments, bot activity) should close. We are seeing older applications are not closing. 

**To Reproduce**

Examples:
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/225
https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/166

**Expected behavior**
After 10 days a warning message should be added to the application, if there are no comments after the warning message, the client's application should close.

**Comment by fabriziogianni7** [comment]
Updated the workflow file with
```
operations-per-run: 1000
ascending: true
```
          
 This is needed to start from the oldest issue and increase the operation limit to 1000.
 
 since there are many issue, the action is reaching the api limit. over time this will close all inactive issues.
 currently 237 issues were marked with stale label
 https://github.com/filecoin-project/filecoin-plus-large-datasets/issues?q=is%3Aopen+is%3Aissue+label%3AStale

**Comment by fabriziogianni7** [comment]
the workflow file: https://github.com/filecoin-project/filecoin-plus-large-datasets/blob/main/.github/workflows/close-inactive-iussues.yml

**Comment by fabriziogianni7** [comment]
@simonkim0515 let's have an eye on this
